# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 'master'

pool:
  name: Default
  demands:
  - Agent.Name -equals teamhd

steps:
- script: |
    docker build . -t microwish
  displayName: 'Build Docker'

- script: |
    docker save -o microwish.tar microwish
    scp -i ~/.ssh/azureuser.pem ./microwish.tar azureuser@20.16.253.47:~/microwish.tar
    scp -i ~/.ssh/azureuser.pem ./microwish.yml azureuser@20.16.253.47:~/microwish.yml
    ssh -i ~/.ssh/azureuser.pem azureuser@20.16.253.47 'docker load -i ~/microwish.tar'
    ssh -i ~/.ssh/azureuser.pem azureuser@20.16.253.47 'rm ~/microwish.tar'
  displayName: 'Copy to Cloud'

- script: |
    ssh -i ~/.ssh/azureuser.pem azureuser@20.16.253.47 'docker compose -f microwish.yml up --force-recreate -d'
    ssh -i ~/.ssh/azureuser.pem azureuser@20.16.253.47 'rm microwish.yml'
  displayName: 'Run Microservice'

- script: |
    sonar-scanner \
      -Dsonar.projectKey=mircoWishlist \
      -Dsonar.sources=. \
      -Dsonar.host.url=http://10.0.40.174:9000 \
      -Dsonar.login=sqa_8d41b5ce316e55e1d7f8b327966e64be61729424
  displayName: "Verify Application"
  condition: always()